### ISSUE TITLE
ACF Blocks Todo list

### ISSUE THREAD

**Issue by elliotcondon** [AdvancedCustomFields/acf#71]
Hi all 👋,

Welcome to the ACF Blocks todo list. Here you will find all the items we are working on for the upcoming [ACF Blocks](https://www.advancedcustomfields.com/blog/acf-5-8-introducing-acf-blocks-for-gutenberg/) feature.

## Bugs
- [x] Unload prompt always shows even after post is published
- [x] Field value is lost when deleting / recreating a field with the same name
- [x] Default values are not loaded in render_callback
- [x] Prevent "edit html" option
- [x] Duplicate Block is not working
- [x] Reusable Block is not working
- [x] Conflicting input names cause issues with duplicate fields (radio)
- [x] Field widths in sidebar should be ignored (100% width CSS override)
- [x] Fix "reordering" rows not affecting preview (rep/flex row index number => string)

## Features
- [x] Allow "alignment toolbar' to be disabled / customized
- [x] Support the "anchor" setting for table of contents
- [x] Use icon in alignment toolbar to switch between edit/preview
- [x] Add setting for default mode (edit/preview)
- [x] Add setting for default align (full, wide, left, right)
- [x] Add setting to restrict mode
- [x] Allow render_callback to provide different front/back markup
- [x] Add render_template setting to avoid callback function
- [x] Add setting to restrict post types

## Ideas
- [x] Save values using field name instead of field key
- [x] WP renders all dynamic blocks on "edit page load" (see `wp.apiFetch.createPreloadingMiddleware()` inline script). Take advantage of this to avoid AJAX preview requests on initial load.
- [x] Use "acf/prepare_field" to change input key to name. Add hidden inputs for "_acf_reference"
- [x] Add post_id value to $block parameter in callback
- [x] Add JS actions during "switch" and "render" events.

## Tasks
- [x] Write documentation for `acf_register_block()` function.
- [x] Write documentation for ACF Blocks feature.

Please leave any comments below, but try not to bloat this ticket into a chatroom.

Thanks
Elliot

**Comment by jjarolim** [comment]
Hi Eliot - 

Bugs: Edit Mode: Multiple Instances of the same block on the same page: Radio Select Javascript interferences. Maybe testing required with all types of input components.

![radio-javascript-interference](https://user-images.githubusercontent.com/16276841/47428233-f1feba00-d792-11e8-83f7-38cf5f86495b.gif)

**Comment by elliotcondon** [comment]
Thanks @jjarolim - I've just added this to the to-do and already know the fix :)

**Comment by nick6352683** [comment]
It's amazing how quickly you fixed the bugs in just a few days. That said, on your web site, I opened 2 new support tickets for a whole new set of bugs regarding WP 5.0 beta1. 

Thanks for all the hard work,
Nick.

**Comment by elliotcondon** [comment]
@nick6352683 Thanks! I'll reply to your tickets shortly

**Comment by jjarolim** [comment]
Hi Eliot -

Cool thanks for fixing "Conflicting input names cause issues with duplicate fields (radio)". 
Is there any chance to test the current build with your fixes? 
Or do you have any release date for beta2?

Or am I blind for not finding the current download?

Thanks ;-)

- Johannes

**Comment by NewJenk** [comment]
Great progress @elliotcondon, when can we expect Beta 2?

Keep up the good work!

**Comment by elliotcondon** [comment]
@jjarolim @NewJenk Aiming to release ACF 5.8.0-beta2 today!

**Comment by nick6352683** [comment]
Totally understandable...

**Comment by jjarolim** [comment]
**5.8 Beta 2: w00t !!**

I can see ALOT of improvements - not only the one bugfix.

THANKS Eliot - That thing is becoming better and better!
I'll currently developing a project with it and will report if i find something.

Thanks again and
best regards from Salzburg, Austria!

- Johannes

**Comment by nick6352683** [comment]
I totally agree with Johannes above: That said, the new beta2 version is crashing my theme's customizer, I'm getting just a white screen, which is an indication for some sort of a JavaScript issue. Deactivating ACF brings back  the customizer. This happens with both WP 4.9 / Gut. 4.1.1, and WP 5.0 beta1. 

Disclosure: I am using the same code as I used n my functions to register the blocks from ACF 5.8 beta1, and not the new one for beta2, so that could be it (hopefully). I will try the new blog registration code on a fresh WP installation and hope that that was the cause and everyone can learn from it... I'll report back my findings here...

**Comment by elliotcondon** [comment]
Hi @nick6352683 Thanks. Will test out customizer today.

**Comment by MakiBM** [comment]
I've been playing with that for a bit and there's one thing that concerns me. It seems to be using ServerSideRender which has to make a round per each update. It's meant as a fallback for a legacy code from what I learnt. Are there any plans to enhance that to `gutenberg` way? Maybe with use of react html parser pkg or even dangerouslySetInnerHTML. NOt sure on possibilities here and how far you could consider as scope of ACF interest. More of a question rather than any solid idea to drop in...

**Comment by elliotcondon** [comment]
Hi @MakiBM Thanks for the feedback.

Yes, we are currently using AJAX to integrate our PHP field framework into Gutenberg's JS UI.
This transition stage is a tricky one for ACF, but if WordPress continues to move towards a full JS admin, we will have to adopt the same direction too.

**Comment by nick6352683** [comment]
Hi @elliotcondon,

Xampp on Windows 7 Pro
WP 5.0 beta 2 - fresh installation
ACF Pro beta2 - second release (today's release) - No other plugins.

My customizer started working again. However, as long as ACF is activated, I cannot update an existing page/post, or publish new ones. Deactivating ACF, things work again.

Initially I thought this was a Theme issue, but I get the same issues exist with the Twenty Nineteen theme as well. Hopefully this is not an ACF issue, but WP, which will be fixed by beta3,4, RC1 or even with the final version.

Thanks,
Nick.

**Comment by elliotcondon** [comment]
Hi @nick6352683 Thanks for the bug report. I'll do some testing today and report back.

**Comment by Jilson** [comment]
Hi Elliot, Really appreciate all the work you are doing with ACF and Gutenberg. It is looking amazing already! One bug I am running into consistently is related to duplicating posts. It seems that styles inside of Wysiwygs get stripped or serialized incorrectly, resulting in the below image. Would love to know if this is a bug or a problem with how I have programmed the render callback. Thank you!
![image](https://user-images.githubusercontent.com/5481759/47934056-8522a880-de93-11e8-978f-16d5d7da71f5.png)

**Comment by Jilson** [comment]
@elliotcondon Suggestion for a feature would be a way to register block editing inside of blocks. To make a completely seamless Gutenberg experience, it would be great to not have to use wysiwyg editors at all for content areas inside of blocks, but to rather use the content blocks. A perfect example of what this type of functionality would be like the newer default "Media & Text" Block.

**Comment by elliotcondon** [comment]
Hi @Jilson This is the long term plan. Currently, we are bridging the gap between Gutenberg's JS React based design with ACF's PHP based architecture.

**Comment by elliotcondon** [comment]
@Jilson As for the Post Duplicator issue. Can you please notify the Post Duplicator devs? Can you also check the DB post_content of the 2 posts (original and duplicated)? Perhaps the issue is occurring in the DB before ACF is rendering anything.

**Comment by jjarolim** [comment]
FYI: Small Hack solved the problem in acf-blocks.js in line 138 (btw. thanks for not minifying it yet):

- var result = wp.blocks.registerBlockType( blockType.name, blockType );
+ var result = wp && wp.blocks && wp.blocks.registerBlockType( blockType.name, blockType );

May not be the final fix but would work for now ;-)

br from Salzburg, Austria
- Johannes

**Comment by elliotcondon** [comment]
Hi @jjarolim 

Thanks mate. I ran into this issue a few days ago too.
I'll aim to release a beta3 soon to fix these minor bugs :)

**Comment by jjarolim** [comment]
Hi Eliot -

Any chance you insert the page id - where the currently rendered block is embeded into - to $block?
Currently i don't see a way how i get that if i render the block in the backend.

In the frontend, i use get_the_ID()
In the backend, i tried get_the_ID, global $wp_query, get_query_var('post'), $_GET['post'], etc. - nothing gives me the current page/post ID.

thanks!

- Johannes

**Comment by elliotcondon** [comment]
Hi @jjarolim Great idea, and one that I have recently added :)

I have added a `$post_id` parameter to the render_callback & render_template.
This will be included in the next beta version!].

**Comment by nick6352683** [comment]
Hi Elliot,

This is not a bug, but a feature not fully implemented for the Blocks. The widths are correctly ignored in the Sidebar (inspector). However, when we have many fields (attributes) in a block, many of us (at least me) organize the fields in Accordions. In this case where the fields are within Accordions, the widths inside the Inspector are honored (not ignored). Any chance of ignoring the widths of fields in Accordions  for the Inspector?

Thanks,
Nick.

**Comment by jjarolim** [comment]
Hi Nick -

Any timeline for beta3?

Additionally, FYI, last week I noticed that it's not a good idea to start the main wp loop inside a acf gutenberg block template.

`while (have_posts()): the_post(); global $post; echo $post->ID; endwhile;`

used in a block template seems to cause a infinite loop.

Besides of the question if using the loop inside a block template is something sane to do (i forgot a code snippet after copy-paste) - it's crashing wp. It seems you reset the main loop before rendering the block template somehow - maybe there is a possibility to reset it to a state where one can use it - gets nothing but breaks nothing either?

BR from Salzburg,

- Johannes

**Comment by nick6352683** [comment]
Hi Johannes,

I'm sure Elliot is waiting for the WP RC due out today. They had a one day delay, and it seems that they will be pushing the final version for the January date. I'll let Elliot respond to you though, as he is the right person to respond to you in this case...

**Comment by jjarolim** [comment]
Hi Nick - Thanks for the fast feedback: just sharing infos if I notice something - no pressure!

Best regards from Salzburg, Austria!

- Johannes

**Comment by mario-neuhold** [comment]
Hi Elliot,

thanks for getting beta3 out so fast and your hard work on ACF Gutenberg in general.

Regarding the changelog:
- Added alias function `acf_register_block_type()` for better naming consistency.

Seems like other functions got renamed as well, but are missing an alias. 
When adding a new field group the Block list is empty. When selecting an existing field group for a block, I get this error in the Location tab:

![acf-beta3-acf_get_blocks](https://user-images.githubusercontent.com/29606929/48906266-35b51400-ee64-11e8-804c-6bcb90f2a644.PNG)

I found a way to fix it by adding the alias in `\advanced-custom-fields-pro\includes\blocks.php`.

At the end of the file I added ...
```
function acf_get_blocks() {
	return acf_get_block_types();
}
```

Not sure if `acf_get_block_type( $name )` and `acf_remove_block_type( $name )` need alias as well?

**Comment by wpmark** [comment]
I can confirm I am also getting this error too with Beta 3.

**Comment by jjarolim** [comment]
I can confirm that Mario's addition to the end of the blocks.php is a working fix for that if you want to work with beta3.

**Comment by nick6352683** [comment]
@mario-neuhold: Your solution saved my thanksgiving !!! Last night I was so bummed (for about 5 minutes), then decided to develop with beta 2, and execute with beta 3, but your little code eliminated all that.

Thanks again,
Nick.

**Comment by nick6352683** [comment]
Well, not exactly after all... It solves in editing the blocks and creating new ones, and on the front end all is well as well, but when you edit a page that contains previously created blocks you get a message "Your site does not include support for the acf/qtsection block. You can leave this block intact or remove it entirely".

What am I missing here?
![capture](https://user-images.githubusercontent.com/5131681/48919282-b2d19080-ee46-11e8-953c-24e8b5cc5327.PNG)

**Comment by nick6352683** [comment]
Clearing the cache when editing the page, forces for Gutenberg to recognize the blocks again, in case others encounter what I experienced. All is well again...

**Comment by nick6352683** [comment]
One quick suggestion to make things even better...

In a block I have a Color field, and this field has a default value set during the fieldset creation process. Now, while using this field in Gutenberg, there is a text field to manually type in and replace the default color, and a "clear" button. Once I use either one of these methods, and change my mind, there is no way to get back the default color (in case I forgot what the default value was). My only recourse at this point, is to delete the block, and start all over again, or temporarily start a new block and get the default value from it...

My suggestion would be, to still have the ability to replace or clear the default color with the text field, but instead of having the clear button have a "default" button, to load the default color set by the developer as intended. With this, we can have all available options available... and this is how the Customizer works as well.

**Comment by elliotcondon** [comment]
Hi @nick6352683 Great idea. I think this is a good improvement for the color picker field. I've just taken a quick look at the customizer but can't find a default value for color pickers. Can you point me in the right direction to check that out?

**Comment by nick6352683** [comment]
I think I was wrong about deleting the color from the text field, the default value gets set, but instead of the clear button we get a default button.

https://www.youtube.com/watch?v=gBF9-HmLcso&feature=youtu.be

**Comment by elliotcondon** [comment]
@nick6352683 I believe this "default" color button may be a custom one in your theme. I've just tested the "Twenty Seventeen" theme and can confirm the the button is named "clear" and does not change the value to a pre-determined default. If you would like to continue this conversation about the color picker, can you please submit a support ticket here: https://www.advancedcustomfields.com/contact/

**Comment by nick6352683** [comment]
We can leave for later on Elliot, as I was at the core meeting today and felt your anxiety, Dealing with these arrogant people should be more than enough for you now...

Thanks.

**Comment by f4w-pwharton** [comment]
@elliotcondon Can you please add an JS event that fires (every time) after the preview loads so we can do things like initialise a slider?

Perhaps another that is called when switching away to the editor view (/just before the ajax call).

i.e. on preview load and unload

**Comment by elliotcondon** [comment]
@f4w-pwharton Great idea. I'll add this to the list.

**Comment by mario-neuhold** [comment]
@elliotcondon 
Facing an issue that sounds related to "[x] Default values are not loaded in render_callback". 

It seems like default values in the render_callback are only working in the backend preview, not in the actual rendered frontend. 

If we create a block that has only one field and that field has a default value set and insert it into a post, it looks good in the block editor, but bad in the frontend where get_field() just returns NULL instead of the expected default_value. 
That's because there is no information about the field in the database yet, only the block ID. Hence ACF can't look up the defined default_value of the field - because there is no field at all.

So despite the positive preview in the backend, the save hook actually calls the render_callback again where the output is still NULL. You have to pro-actively change the value of the radio button to successfully save anything to the db. 

Here is an example gist for a block field definition and a simple template:
https://gist.github.com/mario-neuhold/313ba94a4cf48b835c043d0b1b7ee4fa

We chased the difference between editor + frontend down and found the class `ACF_Local_Meta()->pre_load_reference()` in `\advanced-custom-fields-pro\includes\local-meta.php` filtering `acf/pre_load_reference` which gets applied in `acf_get_reference()` of `\advanced-custom-fields-pro\includes\api\api-value.php`. 

Unfortunately, no idea for a solution whatsoever. For now we have to put the desired default_value in the render_callback template as well.

**Comment by nick6352683** [comment]
Hi Mario, Elliot,

I had reported this annoyance to Elliot since beta 1, and I think this is more of a Gutenberg issue more than an ACF one. Nevertheless, I read this yesterday at the #core-editor channel and I'm not sure, but I think this is similar what they are discussing here. I wish they had better documentation to make Elliot's like easier...

https://wordpress.slack.com/messages/C02QB2JS7/convo/C02QB2JS7-1547086365.456000/

**Comment by elliotcondon** [comment]
Hi @mario-neuhold 

Thanks for the bug report. I'll add this to our to-do list and hopefully find a fix.

**Comment by onetrev** [comment]
Maybe this a really bad idea, and this is probably where just using fields outside of the Block Editor is best....  

But what I'm wondering is, is there a way to access a field value from a block on a _different page_? Really bad idea right? But with a regular ACF fields you can just use the post ID, like so: `<?php echo get_field( 'title', 7 ); ?>`

Obviously is can't be that simple because on a page now the block could be used multiple times so the field would be used multiple times, so you couldn't just use the page ID. But is there a way? Should / could this be added down the track?

**Comment by elliotcondon** [comment]
@onetrev This has been requested a few times, and I'll be sure to think about this during my time working on ACF Blocks. I'm not sure if it will be possible, or if it something that should be allowed, but I'll keep it in mind.

**Comment by korynorthrop** [comment]
> I have added a `$post_id` parameter to the render_callback & render_template.

Did this get included in 5.8.0-beta3? I am trying to access the post_id within a render_template partial, but am not having any success. Thanks!

**Comment by elliotcondon** [comment]
@korynorthrop Yes. You should be able to use the `$post_id` parameter within your 'render_template' file.

**Comment by korynorthrop** [comment]
Thanks, Elliot. I didn't see it in the documentation or when I browsed through the code. Apparently I just overlooked it. Everything is working fine, sorry to waste your time!

**Comment by elliotcondon** [comment]
Announcement: ACF PRO 5.8.0-beta4 released! https://www.advancedcustomfields.com/blog/acf-pro-5-8-0-beta4/

**Comment by robwent** [comment]
Are there any plans to extend the asset loading block options?

As an example, say I wat to use a carousel script. I have to add the script location in the block configuration to get it working in the editor preview.
But if I use multiple carousel blocks on one page then it loads the script multiple times (Or different blocks that require the same script).

If it could enqueue already registered files by their handles rather than adding the script location, wouldn't WordPress then handle the duplication problems?

**Comment by elliotcondon** [comment]
Hi @robwent 

Can you please test and confirm that ACF Blocks are loading your scripts multiple times?
The `enqueue_script` setting does use the `wp_enqueue_script()` function to avoid this.

**Comment by robwent** [comment]
Hi @elliotcondon 

If you look at the source of this page: https://bit.ly/2lBbQF9 you should see owl.carousel.js loading three times from the theme's assets directory.

This comes from 3 different blocks that require the same script but might be used independently or together on the same page.

```
	// Mini Carousel
	acf_register_block_type( array(
		'name'            => 'envoy_mini_carousel',
		'title'           => __( 'Trio tile block' ),
		'description'     => __( '' ),
		'render_template' => 'template-parts/blocks/mini-carousel.php',
		'category'        => 'formatting',
		'icon'            => 'slides', // https://developer.wordpress.org/resource/dashicons/
		'keywords'        => array( 'carousel, cards, mini, slides, slider' ),
		'enqueue_script'  => get_template_directory_uri() . '/assets/js/owl.carousel.js',
		'enqueue_style'  => get_template_directory_uri() . '/assets/css/owl.carousel.min.css',
	) );

	// Carousel Postcards
	acf_register_block_type( array(
		'name'            => 'envoy_carousel_postcards',
		'title'           => __( 'Postcard Carousel' ),
		'description'     => __( '' ),
		'render_template' => 'template-parts/blocks/carousel-postcards.php',
		'category'        => 'formatting',
		'icon'            => 'slides', // https://developer.wordpress.org/resource/dashicons/
		'keywords'        => array( 'carousel, slides, slider, postcards' ),
		'enqueue_script'  => get_template_directory_uri() . '/assets/js/owl.carousel.js',
		'enqueue_style'  => get_template_directory_uri() . '/assets/css/owl.carousel.min.css',
	) );

	// Testimonials
	acf_register_block_type( array(
		'name'            => 'envoy_testimonials',
		'title'           => __( 'Testimonials' ),
		'description'     => __( 'Rotates Testimonials' ),
		'render_template' => 'template-parts/blocks/testimonials.php',
		'category'        => 'formatting',
		'icon'            => 'slides', // https://developer.wordpress.org/resource/dashicons/
		'keywords'        => array( 'testimonial', 'testimonials', 'slider', 'carousel' ),
		'enqueue_script'  => get_template_directory_uri() . '/assets/js/owl.carousel.js',
	) );
```

Looking at the code in /pro/blocks.php the `acf_enqueue_block_type_assets` function generates a handle from the name of the block. So each of these blocks gets a unique handle even though they require the same scripts.

```
// Generate handle from name.
	$handle = 'block-' . acf_slugify($block_type['name']);
```

If I could register these scripts in the themes functions.php file and then add an array of handles to the block for the required scripts then I could also use the other options like dependencies and version numbers.

At the moment I think the only option would be to merge all the settings into one block.

Another example: If the theme uses bootstrap and requires the js file for things like transitions on the menu then it would probably be loaded globally by the theme.
If I then create a block to use the bootstrap accordion which might only be used on some pages, it won't work in the admin area unless the bootstrap js file is loaded, but if I add this to a block the handle would be different to the one specified in the functions file and the script would be loaded twice.

Hope that makes sense.

**Comment by elliotcondon** [comment]
Hi @robwent 

Thanks for the reply and information. In this case, I suggest using the "enqueue_assets" callback to better control the enqueued scripts. Using a callback will allow you define the enqueue handle and avoid this issue.

Note: The "enqueue_script" setting is intended for a simple and quick "block unique" JS file, not a "dependency" or "library" that might be included in other block types.

The "enqueue_assets" callback will offer you the perfect solution for this. I'll leave it with you to read up on :)

**Comment by robwent** [comment]
@elliotcondon oh wow, sorry, I have no idea how I missed that one.
Apologies for wasting your time!

**Comment by robwent** [comment]
Sorry to be a pain but I can't get this to work at all.

I've registered the owl script in my functions.php file and added the 'admin_enqueue_scripts' action to load the same scripts in the admin area as well as the frontend.

```
function envoys_scripts() {
	
	...

	wp_register_script( 'envoys-owl-carousel', get_template_directory_uri() . '/assets/js/owl.carousel.js', array('jquery'), '0', true );

	...
}
add_action( 'wp_enqueue_scripts', 'envoys_scripts' );
add_action( 'admin_enqueue_scripts', 'envoys_scripts' );
```

If I then use the enqueue_assets for the block to enqueue the registered script:

```
'enqueue_assets'  => function () {
			wp_enqueue_script( 'envoys-owl-carousel' );
		},
```

This works fine for the frontend but the script doesn't load in the admin area.

If I change the envoys_scripts function to enqueue rather than register then the script loads in the admin area.

So it seems that enqueuing an already registered script will work on the frontend but not in the admin (even though the admin_enque_scripts action is working).

Is there anything obviously wrong with the way I'm trying to do this?

**Comment by elliotcondon** [comment]
Hi @robwent 

Thanks for the reply. If your "envoys-owl-carousel" script is not enqueuing, I would suspect the issue is due to the timing of events. It could be possible that the ACF Block "enqueue_assets" callback is running BEFORE your "admin_enqueue_scripts" function due to the default priority of 10.

I suggest that you don't use the wp_register_script() function at all, and enter these settings directly into the wp_enqueue_script() function as shown in this doc: https://www.advancedcustomfields.com/resources/acf_register_block_type/

**Comment by robwent** [comment]
Hi @elliotcondon 

That's actually what I tried first, but it caused a lot of errors in the admin and I thought it was because I was using enqueue_script multiple times for the same script in different blocks.

The file that registers the blocks is included after the enqueued scripts are added in the functions file but I'm not totally sure about priorities. I'll give it another go tomorrow!
